favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5694963
  brandStrength: 0.1740376076195389
  lightness: 0.6693097
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  rhythmicContrast: 0.2229478
typography_spectrum: 0.8598538967780769
layout_spectrum: 0.3283582
analytics:
  twitter: null
  google: null
  facebook: null
name: AcevedoPhoto
